### ISSUE TITLE
Changing user points

### ISSUE THREAD

**Issue by slamball** [branjos/Clan_Bot-Wiki#11]
Currently updating all clan members current points, having an issue with only adding 1 point. I'm updating points, checking points and some are off by 1. After trying to add 1 point it resets users point to previous amount.

**Comment by slamball** [comment]
ie our spreadsheets show 20 points, bot shows 10. add 10 points, end up at 19. add one point and resets back to 10

**Comment by branjos** [comment]
I'll need to investigate the off by one (19 instead of 20) error. 

The edituserpoints command only takes total numbers. I think it would be better for add/remove instead of edit commands. I will  change this

**Comment by branjos** [comment]
Both of these should be addressed now.
