### ISSUE TITLE
add bumps field to user

### ISSUE THREAD

**Issue by branjos** [branjos/Clan_Bot-Wiki#112]
Some clans still use bumping or posting on the forums as a way to track promotions and would like it to be a separate field on the user.

**Comment by branjos** [comment]
After talking to Blue - we think that it'll be cool if we could allow clans to create their own fields and allow them to add and remove a number from it. Should be an interesting feature to add. I think its a good idea

**Comment by Leslie-fay** [comment]
moving to other github
