### ISSUE TITLE
Clan Bot didn't reset Citadel

### ISSUE THREAD

**Issue by JustNeo007** [branjos/Clan_Bot-Wiki#126]
Clan Bot knew when the citadel will reset; however, when the time came it didn't give the message that the Citadel Reset, and when I _a printallcaps I get all the results from the previous build tick. The bot failed to start over on tracking.

**Comment by branjos** [comment]
Hm, this is odd. Clan name?

**Comment by branjos** [comment]
believe this is fixed.
