### ISSUE TITLE
Create Poll functions

### ISSUE THREAD

**Issue by branjos** [branjos/Clan_Bot-Wiki#3]
Polling the users is often a good way to tell how something should be done or what the people want. Polling is a great tool for clan leaders. 

Polls should be only available to validated users. I think they should also be anonymous, and set certain visibility based on rank.

**Comment by branjos** [comment]
This is a little big for 1.1 - I'd rather shoot for 1.2

**Comment by Leslie-fay** [comment]
not moving as don't think we need it with the direction that bot has gone :)
