### ISSUE TITLE
Spreadsheet total points is wrong

### ISSUE THREAD

**Issue by Cabola** [branjos/Clan_Bot-Wiki#55]
1) It doesn't add the discord points, it's missing from the calculation.
2) It doesn't use the correct row number for people.

Ex. in my clan it uses row 59 for me but my row number is 89 within the data sheet. The person who is 59 in the data sheet is using 94 in the points calc. So somehow it's grabbing the wrong row number..

**Comment by branjos** [comment]
Thank you, I'll check this out and get back to you!

**Comment by Cabola** [comment]
I fixed the wrong row usage by applying the correct formula to the total points column on the points calculation sheet, and ever since doing that it's been using the right rows. So don't know what caused it to error in the first place, but it works now. I just followed the instructions you gave to Rob on discord.

In regards to the discord points you just need to add another column to the data sheet which notes if the person has validated with discord, and then add that into the total points formula. :)

**Comment by branjos** [comment]
Yes, the data sheet will get updated at the next update as long as I get it in the code in time. It will simply show 1 or 0 for UsingDiscord and I'll add to the formula something like (Config!$B$21 * Data!K#) which will either return full discord points or 0.

At least that is my concept - will need to test and ensure it works correctly!

**Comment by Cabola** [comment]
Well I can say it does. I made our own sheet called Discord where I just list all peeps name from the data sheet with the =arrayformula(Data!A2:A) and the column next to the name with 1 or 0 as you said too. Then in the Points Calculations sheet I added at the end of the formula  "+ (Discord!B# * Config!$B$21)" 👍

**Comment by branjos** [comment]
I have added the Using discord to the spreadsheet. A updated formula will be coming out later today
1.2.3 release
