### ISSUE TITLE
if possible add clan log list to google sheet 

### ISSUE THREAD

**Issue by Leslie-fay** [branjos/Clan_Bot-Wiki#61]
lesliefay - Today at 4:23 PM
okay well I know Branjos has it on the list to do a log similar to the citadel log that runs when new people join, leave, and names are changed
if that could be incorporated into the spread sheet would that help?

Fari - Today at 4:24 PM
mhm ofc

lesliefay - Today at 4:24 PM
okee let me add that for him to look into 

Fari - Today at 4:24 PM
ty

lesliefay - Today at 4:24 PM
no problem
okee I am going to propose it as being its own sheet within the sheets he already provides for us if possible just so you know how I am wording it

Fari - Today at 4:28 PM
that'd be great

**Comment by branjos** [comment]
This is 100% possible, however, you will find that this list will become unruly and long after a while making the sheet's performance slow down. 

I'm thinking maybe put in the last 100 activities and overwrite them each update?

**Comment by branjos** [comment]
released in 1.2.5
