### ISSUE TITLE
make a _help betacommands

### ISSUE THREAD

**Issue by Leslie-fay** [branjos/Clan_Bot-Wiki#65]
Beta commands are kinda lost in info now so need to write them down or make a hidden command to retrieve them i.e _help betacommands

**Comment by Cabola** [comment]
There's a lot of commands that are missing from the _help on the bot, I tend to just go use the bot commands spreadsheet https://docs.google.com/spreadsheets/d/1Raf1nSmyG_TLWtQ9_Fme7Dn2BGbYygWoDaV3XMRxJJ0/edit#gid=0

**Comment by branjos** [comment]
If you use _help admin, or _help settings you'll get a more in-depth list of commands for each module. Looking at the list from _help just now it does appear they are all there (just bunched together way too much)

**Comment by Leslie-fay** [comment]
I will be working on updating the spreadsheet this week, please PM me on discord or comment on the issue I made on here if you know of the ones missing @Cabola

**Comment by Cabola** [comment]
Ahh I see now all you had to do was _help admin as it explains all the admin commands. Ex. I wanted more info on the "addrecruit" so I've been trying to do it like _help addrecruit or _help admin addrecruit or _help _admin addrecruit as I thought you could get the info of a single command by it self. My bad..

**Comment by branjos** [comment]
It isn't specified anywhere (I generally dont use the _help, like ever) and I thought that it said in the footer instructions for the _help admin etc.. I'll be updating that to make it easier to follow

**Comment by branjos** [comment]
already implemented apparently
