### ISSUE TITLE
Ways to handle alt accounts

### ISSUE THREAD

**Issue by Leslie-fay** [branjos/Clan_Bot-Wiki#69]
From discord convo 

branjos - Today at 1:25 PM
Hm, I've often been pondering how to handle ALTs. Every clan has them and does something different with them. Couple of thoughts here:

1. Have a true or false flag that says alt and if it's true don't print them in promotion list
2. Have a main field where it'll list the mains username (if filled) and again not print on promotions. Then have an alt list of the same type. Both on user info command
3. Have a whole seperate listing of configuration for ALTs, allowing clans to choose what ALTs get

**Comment by branjos** [comment]
released in 1.2.5
