### ISSUE TITLE
if possible add a paypal button instead of the link in _about

### ISSUE THREAD

**Issue by Leslie-fay** [branjos/Clan_Bot-Wiki#72]

**Comment by Leslie-fay** [comment]
oh boo you said this wasn't possible but will keep it open as low priority to put more research into :)

**Comment by Leslie-fay** [comment]
![image](https://user-images.githubusercontent.com/35538910/35229758-d351b006-ff59-11e7-9f51-e4559395f7cb.png)

**Comment by branjos** [comment]
Button is going to be a no-go for now :(
