### ISSUE TITLE
find a way to flag clans not using bot in discord

### ISSUE THREAD

**Issue by Leslie-fay** [branjos/Clan_Bot-Wiki#85]
branjos - Yesterday at 7:44 PM
Mmm
That's 9 difference now.
Maybe I can put an active flag on the clans. When the bot leaves a server, make the clan inactive and don't update the clans that aren't active. Saves the data but doesn't update clans that shouldn't be

**Comment by branjos** [comment]
inactive flag released. 30 days of no commands = inacitve
