### ISSUE TITLE
This clan has already been registered in a different discord server.

### ISSUE THREAD

**Issue by Playdoh1** [branjos/Clan_Bot-Wiki#9]
Hi, i tried to register my clan with clan bot in discord and got the following message -

 
This clan has already been registered in a different discord server. For additional information, please read the wiki reference in the _about command. 

Discord name: Playdoh#8647

**Comment by branjos** [comment]
This happened because you already had the clan registered to your server. I marked this as a bug so I can address the error message to better reflect the problem. 

Thanks for creating this issue!

**Comment by branjos** [comment]
I have added more informative error messages to help denote whether a clan has been created on the current server or if it is on a different server.
