### ISSUE TITLE
 messages for when we do a _b command and the clan isn't updated

### ISSUE THREAD

**Issue by Leslie-fay** [branjos/Clan_Bot-Wiki#99]

**Comment by branjos** [comment]
i dont remember what this was about. Leslie can you elaborate?

**Comment by Leslie-fay** [comment]
What it was is that when we did a _b getclanusers etc and the clans data hadn’t pulled it wouldn’t produce a message.

**Comment by branjos** [comment]
addressed in 2.0.0 RC4
